org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=1.20.1-47.4.2
fabric_loader_version=0.17.2
fabric_api_version=0.92.6+1.20.1
architectury_version=9.1.12

mod_id=vskinetic
mod_name=VS: Kinetic
mod_version=0.1.0
archives_base_name=vs-kinetic
maven_group=org.valkyrienskies.vskinetic

vs2_version=2.4.7
vscore_version=1.1.0+b714ef303e
kotlinforforge_version=4.11.0

enabled_platforms=forge,fabric
