architectury {
    common(rootProject.enabled_platforms.split(","))
}

dependencies {
    modApi "dev.architectury:architectury:${rootProject.architectury_version}"
    modApi("org.valkyrienskies:valkyrienskies-120-common:${rootProject.vs2_version}") {
        transitive = false
    }
    implementation("org.valkyrienskies.core:api:${rootProject.vscore_version}") {
        exclude group: "org.joml", module: ""
    }
    implementation("org.valkyrienskies.core:util:${rootProject.vscore_version}") {
        exclude group: "org.joml", module: ""
    }
}

test {
    useJUnitPlatform()
}
